package com.kuromitv.nativeapp;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.KeyEvent;
import android.view.View;
import android.view.Window;
import android.webkit.CookieManager;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;

public class MainActivity extends Activity {
    private static final String PLAYER_BASE="https://sinalpublicoetv.vercel.app/?id=";
    private static final String CHANNELS_URL="https://raw.githubusercontent.com/redzinprojects/Kuromi-TV/main/channels.json";
    private static final String CODES_URL="https://raw.githubusercontent.com/redzinprojects/Kuromi-TV/main/codes.json";
    private static final String CACHE_KEY="channels_json";
    private static final int BG=Color.rgb(63,0,0), SURFACE=Color.rgb(90,0,0), RED=Color.rgb(255,51,51), BORDER=Color.rgb(139,0,0), WHITE=Color.WHITE, MUTED=Color.rgb(224,224,224);
    private final Map<String,ArrayList<Channel>> categories=new LinkedHashMap<>();
    private final Map<String,Integer> codes=new LinkedHashMap<>();
    private android.content.SharedPreferences prefs;
    private LinearLayout root,content;
    private WebView player;
    private TextView current,syncStatus;
    private boolean playerMode=false,channelMenuOpen=false;
    private FrameLayout playerScreen;
    private LinearLayout channelMenu,channelList;
    private Button firstChannel,firstMenuChannel;
    private String currentChannelId="",currentChannelName="";
    private static class Channel { final String name,id; Channel(String n,String i){name=n;id=i;} }

    @Override public void onCreate(Bundle state){super.onCreate(state);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);prefs=getSharedPreferences("kuromi",MODE_PRIVATE);categories.clear();seedCodes();showHomeOrLogin();}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private int widthDp(){return Math.round(getResources().getDisplayMetrics().widthPixels/getResources().getDisplayMetrics().density);}
    private boolean isTv(){return getResources().getConfiguration().smallestScreenWidthDp>=600 || widthDp()>=900;}
    private int formWidth(){return Math.min(dp(isTv()?520:420),Math.max(dp(260),getResources().getDisplayMetrics().widthPixels-dp(40)));}
    private void seedCodes(){codes.clear();codes.put("REDZIN",1);codes.put("HENRI24",1);codes.put("30DAYSK",30);codes.put("90DAYSK",90);codes.put("365DAYSK",365);}
    private void seedFallback(){categories.clear();add("Canais Abertos",new String[][]{{"Globo RJ","globorj"},{"Globo SP","globosp"},{"Globo MG","globomg"},{"Globo PE","globope"},{"Globo PB","globopb"},{"Globo RS","globors"},{"Globo ES","globoes"},{"Globo AM","globoam"},{"Globo CE","globoce"},{"SBT","sbt"},{"SBT SP","sbtsp"},{"SBT RJ","sbtrj"},{"Record TV","record"},{"Band","band"}});add("Notícias",new String[][]{{"GloboNews","globonews"},{"SBT NEWS","sbtnews"},{"BandNews","bandnews"},{"CNN Brasil","cnnbrasil"},{"Jovem Pan News","jovempan"}});add("Esportes",new String[][]{{"SporTV","sportv"},{"SporTV 2","sportv2"},{"SporTV 3","sportv3"},{"ESPN","espn"},{"ESPN 2","espn2"},{"ESPN 3","espn3"},{"ESPN 4","espn4"},{"Premiere","premiere"},{"Combate","combate"},{"Cazé TV","cazetv"},{"Band Sports","bandsports"}});add("Filmes e Séries",new String[][]{{"Telecine","telecine"},{"Telecine Premium","telecinepremium"},{"Telecine Pipoca","telecinepipoca"},{"Telecine Action","telecineaction"},{"Universal TV","universal"},{"Studio Universal","studiouniversal"},{"Megapix","megapix"},{"AMC","amc"},{"Paramount Network","paramount"},{"AXN","axn"},{"Syfy","syfy"}});add("Infantil",new String[][]{{"Gloob","gloob"},{"Gloobinho","gloobinho"},{"Nickelodeon","nickelodeon"},{"Nick Jr.","nickjr"},{"Cartoon Network","cartoonnetwork"},{"Discovery Kids","discoverykids"},{"Rá-Tim-Bum","ratimbum"}});add("Documentários e Cultura",new String[][]{{"Canal Brasil","canalbrasil"},{"Arte 1","arte1"},{"Discovery Channel","discovery"},{"History Channel","history"},{"Animal Planet","animalplanet"},{"National Geographic","natgeo"}});add("Variedades e Música",new String[][]{{"Multishow","multishow"},{"GNT","gnt"},{"BIS","bis"},{"MTV","mtv"}});}
    private void add(String n,String[][] v){ArrayList<Channel> list=new ArrayList<>();for(String[] c:v)list.add(new Channel(c[0],c[1]));categories.put(n,list);}
    private TextView text(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setPadding(dp(10),dp(8),dp(10),dp(8));return v;}
    private LinearLayout base(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(isTv()?34:16),dp(isTv()?24:12),dp(isTv()?34:16),dp(isTv()?24:12));l.setBackgroundColor(BG);return l;}
    private GradientDrawable bg(int color,int stroke,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setStroke(dp(stroke),stroke==0?color:RED);g.setCornerRadius(dp(radius));return g;}
    private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(WHITE);b.setTextSize(isTv()?15:14);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setFocusable(true);b.setMinHeight(dp(50));b.setPadding(dp(8),0,dp(8),0);GradientDrawable normal=bg(Color.rgb(139,0,0),1,10);GradientDrawable focused=bg(Color.rgb(178,34,34),3,10);b.setBackground(normal);b.setOnFocusChangeListener((v,has)->b.setBackground(has?focused:normal));return b;}
    private EditText field(String s,boolean pass){EditText e=new EditText(this);e.setHint(s);e.setHintTextColor(MUTED);e.setTextColor(WHITE);e.setTextSize(16);e.setPadding(dp(12),0,dp(12),0);e.setBackground(bg(Color.rgb(45,0,0),1,8));if(pass)e.setInputType(0x81);e.setSingleLine();return e;}
    private LinearLayout.LayoutParams full(int h){return new LinearLayout.LayoutParams(-1,h<0?-2:dp(h));}
    private void showHomeOrLogin(){String u=prefs.getString("user",null);if(u==null)showLogin();else if(validAccess(u))showCatalog();else showRecharge();}
    private boolean validAccess(String u){return u!=null&&prefs.getLong("expires_"+u,0)>System.currentTimeMillis();}
    private void showLogin(){root=base();root.setGravity(Gravity.CENTER);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER_HORIZONTAL);card.setPadding(dp(24),dp(22),dp(24),dp(22));card.setBackground(bg(SURFACE,1,14));TextView t=text("KUROMI TV",32,RED);t.setGravity(Gravity.CENTER);card.addView(t,full(58));EditText user=field("Usuário",false),pass=field("Senha",true);card.addView(user,full(54));card.addView(pass,full(54));Button login=button("Entrar");login.setOnClickListener(v->{String u=user.getText().toString().trim(),p=pass.getText().toString(),saved=prefs.getString("pass_"+u,null);if(saved!=null&&saved.equals(p)){prefs.edit().putString("user",u).apply();if(validAccess(u))showCatalog();else showRecharge();}else toast("Usuário ou senha incorretos");});card.addView(login,full(54));Button register=button("Criar conta");register.setOnClickListener(v->{String u=user.getText().toString().trim();if(u.length()==0||pass.getText().length()==0){toast("Informe usuário e senha");return;}if(prefs.contains("pass_"+u)){toast("Este usuário já existe");return;}prefs.edit().putString("pass_"+u,pass.getText().toString()).putString("user",u).apply();showRecharge();});card.addView(register,full(54));root.addView(card,new LinearLayout.LayoutParams(formWidth(),-2));setContentView(root);login.requestFocus();}
    private void showRecharge(){root=base();root.setGravity(Gravity.CENTER);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER_HORIZONTAL);card.setPadding(dp(24),dp(22),dp(24),dp(22));card.setBackground(bg(SURFACE,1,14));TextView t=text("ACESSO EXPIRADO",26,RED);t.setGravity(Gravity.CENTER);card.addView(t,full(58));TextView info=text("Digite seu código de recarga para liberar os canais.",16,MUTED);info.setGravity(Gravity.CENTER);card.addView(info,full(68));EditText code=field("Código de recarga",false);card.addView(code,full(54));TextView msg=text("",15,WHITE);msg.setGravity(Gravity.CENTER);card.addView(msg,full(48));Button activate=button("Ativar código");activate.setOnClickListener(v->applyCode(code.getText().toString(),msg));card.addView(activate,full(54));Button logout=button("Sair");logout.setOnClickListener(v->{prefs.edit().remove("user").apply();showLogin();});card.addView(logout,full(54));root.addView(card,new LinearLayout.LayoutParams(formWidth(),-2));setContentView(root);activate.requestFocus();loadCodes();}
    private void applyCode(String raw,TextView msg){String u=prefs.getString("user",null),code=raw.trim().toUpperCase();Integer days=codes.get(code);if(u==null){showLogin();return;}String used=prefs.getString("used_"+u,"");if(days==null){msg.setText("Código de recarga inválido.");return;}if((","+used+",").contains(","+code+",")){msg.setText("Este código já foi utilizado.");return;}long old=prefs.getLong("expires_"+u,0),start=Math.max(old,System.currentTimeMillis()),expires=start+days*86400000L;prefs.edit().putLong("expires_"+u,expires).putString("used_"+u,used.length()==0?code:used+","+code).apply();msg.setText("Código ativado: "+days+" dia(s).");new android.os.Handler().postDelayed(()->showCatalog(),900);}
    private void showCatalog(){if(!validAccess(prefs.getString("user",null))){showRecharge();return;}root=base();ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setDescendantFocusability(LinearLayout.FOCUS_AFTER_DESCENDANTS);LinearLayout header=new LinearLayout(this);header.setOrientation(isTv()?LinearLayout.HORIZONTAL:LinearLayout.VERTICAL);header.setGravity(Gravity.CENTER_VERTICAL);TextView title=text("KUROMI TV",isTv()?30:26,RED);title.setGravity(Gravity.CENTER_VERTICAL);header.addView(title,new LinearLayout.LayoutParams(isTv()?0:-1,dp(58),isTv()?1:0));LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.CENTER_VERTICAL);Button refresh=button("Atualizar");refresh.setOnClickListener(v->syncChannels());Button redeem=button("Recarga");redeem.setOnClickListener(v->showRecharge());Button logout=button("Sair");logout.setOnClickListener(v->{prefs.edit().remove("user").apply();showLogin();});actions.addView(refresh,new LinearLayout.LayoutParams(dp(112),dp(52)));actions.addView(redeem,new LinearLayout.LayoutParams(dp(102),dp(52)));actions.addView(logout,new LinearLayout.LayoutParams(dp(78),dp(52)));if(isTv()){header.addView(actions,new LinearLayout.LayoutParams(-2,dp(58)));}else{HorizontalScrollView ah=new HorizontalScrollView(this);ah.setHorizontalScrollBarEnabled(false);ah.addView(actions);header.addView(ah,full(58));}content.addView(header,full(isTv()?64:128));player=new WebView(this);player.setBackgroundColor(Color.BLACK);WebSettings ws=player.getSettings();ws.setJavaScriptEnabled(true);ws.setDomStorageEnabled(true);ws.setMediaPlaybackRequiresUserGesture(false);ws.setLoadWithOverviewMode(true);ws.setUseWideViewPort(true);ws.setSupportMultipleWindows(false);ws.setUserAgentString("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36");CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(player,true);player.setWebChromeClient(new WebChromeClient());player.setWebViewClient(new WebViewClient());content.addView(player,new LinearLayout.LayoutParams(-1,dp(isTv()?390:210)));current=text("Escolha um canal abaixo",17,MUTED);current.setGravity(Gravity.CENTER);content.addView(current,full(48));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);renderCategories();syncChannels();loadCodes();}
    private void renderCategories(){if(content==null)return;while(content.getChildCount()>3)content.removeViewAt(3);firstChannel=null;int cols=isTv()?5:(widthDp()>=600?4:2);for(Map.Entry<String,ArrayList<Channel>> e:categories.entrySet()){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(8),dp(12),dp(12));card.setBackground(bg(SURFACE,1,12));TextView heading=text(e.getKey(),isTv()?21:19,WHITE);heading.setPadding(dp(4),dp(2),dp(4),dp(8));card.addView(heading,full(42));GridLayout grid=new GridLayout(this);grid.setColumnCount(cols);grid.setUseDefaultMargins(false);for(Channel c:e.getValue()){Button b=button(c.name);b.setTag(c);b.setOnClickListener(v->{Channel ch=(Channel)v.getTag();play(ch.id,ch.name);});GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=dp(isTv()?60:56);gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1,1f);gp.setMargins(dp(4),dp(4),dp(4),dp(4));grid.addView(b,gp);if(firstChannel==null)firstChannel=b;}card.addView(grid,new LinearLayout.LayoutParams(-1,-2));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(14));content.addView(card,cp);}if(firstChannel!=null&&!player.hasFocus())firstChannel.requestFocus();}
    private void play(String id,String name){if(player==null)return;if(!playerMode)openPlayerScreen();closeChannelMenu();loadChannel(id,name);}
    private void openPlayerScreen(){playerMode=true;channelMenuOpen=false;getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE);if(player.getParent()!=null)((android.view.ViewGroup)player.getParent()).removeView(player);playerScreen=new FrameLayout(this);playerScreen.setBackgroundColor(Color.BLACK);playerScreen.addView(player,new FrameLayout.LayoutParams(-1,-1));channelMenu=new LinearLayout(this);channelMenu.setOrientation(LinearLayout.VERTICAL);channelMenu.setPadding(dp(14),dp(18),dp(14),dp(18));channelMenu.setBackgroundColor(Color.argb(245,50,0,0));TextView h=text("CANAIS",isTv()?24:21,WHITE);channelMenu.addView(h,new LinearLayout.LayoutParams(-1,dp(48)));TextView help=text("OK abre o canal  •  Voltar fecha o menu",isTv()?14:12,MUTED);channelMenu.addView(help,new LinearLayout.LayoutParams(-1,dp(38)));ScrollView menuScroll=new ScrollView(this);channelList=new LinearLayout(this);channelList.setOrientation(LinearLayout.VERTICAL);menuScroll.addView(channelList);channelMenu.addView(menuScroll,new LinearLayout.LayoutParams(-1,0,1));playerScreen.addView(channelMenu,new FrameLayout.LayoutParams(isTv()?dp(460):-1,-1,Gravity.LEFT));channelMenu.setVisibility(View.GONE);setContentView(playerScreen);buildChannelMenu();}
    private void buildChannelMenu(){if(channelList==null)return;channelList.removeAllViews();firstMenuChannel=null;for(Map.Entry<String,ArrayList<Channel>> e:categories.entrySet()){TextView heading=text(e.getKey(),isTv()?18:16,RED);channelList.addView(heading,new LinearLayout.LayoutParams(-1,dp(38)));for(Channel c:e.getValue()){Button b=button(c.name);b.setOnClickListener(v->{loadChannel(c.id,c.name);closeChannelMenu();});channelList.addView(b,new LinearLayout.LayoutParams(-1,dp(isTv()?58:54)));if(firstMenuChannel==null)firstMenuChannel=b;}}}
    private void loadChannel(String id,String name){currentChannelId=id;currentChannelName=name;player.loadUrl(PLAYER_BASE+android.net.Uri.encode(id));player.requestFocus();}
    private void openChannelMenu(){if(!playerMode||channelMenu==null)return;buildChannelMenu();channelMenuOpen=true;channelMenu.setVisibility(View.VISIBLE);if(firstMenuChannel!=null)firstMenuChannel.requestFocus();}
    private void closeChannelMenu(){if(channelMenu==null)return;channelMenuOpen=false;channelMenu.setVisibility(View.GONE);if(player!=null)player.requestFocus();}
    private void changeChannel(int step){ArrayList<Channel> all=new ArrayList<>();for(ArrayList<Channel> list:categories.values())all.addAll(list);if(all.isEmpty())return;int at=0;for(int i=0;i<all.size();i++)if(all.get(i).id.equals(currentChannelId)){at=i;break;}at=(at+step+all.size())%all.size();Channel next=all.get(at);loadChannel(next.id,next.name);toast(next.name);}
    private void syncChannels(){String cached=prefs.getString(CACHE_KEY,null);if(cached!=null)try{parseChannels(cached);renderCategories();}catch(Exception ignored){}new Thread(()->{try{String json=getUrl(CHANNELS_URL);parseChannels(json);prefs.edit().putString(CACHE_KEY,json).apply();runOnUiThread(()->{renderCategories();if(syncStatus!=null)syncStatus.setText("Catálogo atualizado");});}catch(Exception e){runOnUiThread(()->{if(syncStatus!=null)syncStatus.setText("Catálogo em cache/offline");});}}).start();}
    private void loadCodes(){new Thread(()->{try{JSONObject j=new JSONObject(getUrl(CODES_URL));JSONObject valid=j.optJSONObject("VALID_CODES");if(valid!=null){java.util.Iterator<String> it=valid.keys();while(it.hasNext()){String k=it.next();codes.put(k,valid.getInt(k));}}}catch(Exception ignored){}}).start();}
    private String getUrl(String address)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(address).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestProperty("Cache-Control","no-cache");if(c.getResponseCode()!=200)throw new Exception("HTTP "+c.getResponseCode());BufferedReader br=new BufferedReader(new InputStreamReader(c.getInputStream(),"UTF-8"));StringBuilder s=new StringBuilder();String line;while((line=br.readLine())!=null)s.append(line);br.close();c.disconnect();return s.toString();}
    private void parseChannels(String json)throws Exception{JSONArray cats=new JSONObject(json).getJSONArray("categories");LinkedHashMap<String,ArrayList<Channel>> next=new LinkedHashMap<>();for(int i=0;i<cats.length();i++){JSONObject cat=cats.getJSONObject(i);JSONArray a=cat.getJSONArray("channels");ArrayList<Channel> list=new ArrayList<>();for(int j=0;j<a.length();j++){JSONObject c=a.getJSONObject(j);list.add(new Channel(c.getString("name"),c.getString("id")));}next.put(cat.getString("name"),list);}categories.clear();categories.putAll(next);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    @Override public boolean dispatchKeyEvent(KeyEvent event){if(playerMode&&event.getAction()==KeyEvent.ACTION_DOWN){int key=event.getKeyCode();if(key==KeyEvent.KEYCODE_MENU||key==KeyEvent.KEYCODE_GUIDE||key==KeyEvent.KEYCODE_INFO||key==KeyEvent.KEYCODE_DPAD_LEFT){if(channelMenuOpen)closeChannelMenu();else openChannelMenu();return true;}if(key==KeyEvent.KEYCODE_CHANNEL_UP||key==KeyEvent.KEYCODE_MEDIA_NEXT){changeChannel(1);return true;}if(key==KeyEvent.KEYCODE_CHANNEL_DOWN||key==KeyEvent.KEYCODE_MEDIA_PREVIOUS){changeChannel(-1);return true;}if(key==KeyEvent.KEYCODE_BACK&&channelMenuOpen){closeChannelMenu();return true;}}return super.dispatchKeyEvent(event);}
    @Override public void onBackPressed(){if(playerMode){if(channelMenuOpen){closeChannelMenu();return;}playerMode=false;getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);showCatalog();}else{super.onBackPressed();}}
    @Override protected void onDestroy(){if(player!=null)player.destroy();super.onDestroy();}
}
